[build-system]
requires = ['hatchling', 'hatch-vcs']
build-backend = 'hatchling.build'
# requires = ['setuptools >= 77.0.3']
# build-backend = 'setuptools.build_meta'
# requires = ["uv_build>=0.12.5,<0.13"]
# build-backend = "uv_build"

[project]
dynamic = ['version']

name = 'casual-pre-loader'
description = 'TF2 particle modifications via some wizardry.'
keywords = ['team-fortress-2', 'tf2', 'modding', 'source-games', 'valve-games']

readme = 'README.md'
license = 'GPL-3.0-or-later AND CC-BY-NC-ND-4.0'
license-files = ['LICEN[CS]E*']

authors = [
	{name = 'cueki',email = 'madisonlovett@lovett.dev'},
	{name = 'djsigmann', email = 'djsigmann@protonmail.com'},
]

maintainers = [
	{name = 'cueki',email = 'madisonlovett@lovett.dev'},
	{name = 'djsigmann', email = 'djsigmann@protonmail.com'},
]

requires-python = '>= 3.12'
dependencies = [
	# GUI
	'PyQt6~=6.11',

	# core
	'cappa~=0.32.2',
	'more-itertools~=11.0',
	'packaging~=26.0',
	'platformdirs~=4.9',
	'PyGithub~=2.9',
	'requests~=2.34',
	'rich~=15.0',
	'valve-parsers>=1.2.2',
]

[project.optional-dependencies]
dev = [
	'ruff',
	'ty',
]
doc = [
	'mkdoc',
]

[project.scripts]
casual-pre-loader = 'main:main'

[project.gui-scripts]
casual-pre-loader = 'main:main'

# [[project.maintainers]]
# name = 'cueki'
# email = 'madisonlovett@lovett.dev'

[project.urls]
Homepage = 'https://github.com/cueki/casual-pre-loader'
Documentation = 'https://cueki.github.com/casual-pre-loader'
Repository = 'https://github.com/cueki/casual-pre-loader'
Issues = 'https://github.com/cueki/casual-pre-loader/issues'
Changelog  = 'https://github.com/cueki/casual-pre-loader/blob/main/CHANGELOG.md'

# [tool.setuptools]
# py-modules = ['main']
# [tool.setuptools.packages.find]
# where = ['.']
# include = [
# 	'core/*',
# 	'gui/*'
# ]
# namespaces = true
# [tool.setuptools.package-data]
# backup = ["**/*"]
# data = ["**/*"]

# [tool.uv.build-backend]
# module-root = ''

[tool.hatch.build.targets.sdist]
packages = [
	'main.py',
	'backup',
	'core',
	'data',
	'gui',
]
[tool.hatch.build.targets.wheel]
packages = [
	'main.py',
	'backup',
	'core',
	'data',
	'gui',
]
[tool.hatch.version]
source = 'vcs'

[tool.ruff]
exclude = [
	'.git',
	'.venv',
]
line-length = 140
indent-width = 4
target-version = 'py312'

[tool.ruff.lint]
select = ['E4', 'E7', 'E9', 'F']
ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ['ALL']
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$'
preview = true # allow specifying ignored rules by name rather than by identifier in source code comments

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'
skip-magic-trailing-comma = false
line-ending = 'lf'

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = 'dynamic'
